version: '2'
services:
  integration:
    image: nginx
    volumes:
      - ./scs-commerce.nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - landing-page:landing-page
      - products:products
      - order:order
      - assets:assets
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=scs-commerce.dev
      - NGINX_PORT=80

  landing-page:
    build: ../landing-page
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"

  products:
    build: ../products
    environment:
      PORT: "3001"
    ports:
      - "3001:3001"

  order:
    build: ../order
    environment:
      PORT: "3002"
    ports:
      - "3002:3002"

  assets:
    build: ../assets
    environment:
      PORT: "3003"
    ports:
      - "3003:3003"
